Light dark mode graph: When switching appearance mode in View Menu, Graph will change color
BP-TPSE-Projektgruppe-80/NaPyTau pull request #15
Opened 2024-11-30 16:13 UTC by Kobsel

### Summary

Please summarize the changes of this PR, starting with _why_ the PR is needed.

---

### PR checklist

- [ ] I have written tests that fail without my changes. _Or I did not add them on purpose._
- [ ] I have included instructions on how to test this, assuming they are not already apparent from the linked issue.

---

### Depends on

- [ ] Depends on #0

### Closes/Fixes/Related to

* Fixes #0 
* Closes #0 
* Related to #0

2024-11-30 23:44 UTC, Benedikt-Brunner requested changes
Had a look at the UI, i like it 👍 
I didn't have much to say here, just some left over print statements.

These changes should be moved to the Graph Widget after it gets separated in the base PR.

Also @julius-kress needs to approve the layouting changes, as i don't have the expertise to comment on that.

2024-11-30 23:44 UTC, Benedikt-Brunner commented on napytau/gui/gui_app.py
> +        print("Fall1")
These print statements should probably be removed

2024-11-30 23:44 UTC, Benedikt-Brunner commented on napytau/gui/gui_app.py
> +    print(appearance)
remove this aswell

2024-11-30 23:44 UTC, Benedikt-Brunner commented on napytau/gui/gui_app.py
> +        self.appearance_mode.trace_add("write", self.update_plot)
cool

2024-12-02 17:06 UTC, julius-kress commented
> Had a look at the UI, i like it 👍 I didn't have much to say here, just some left over print statements.
> 
> These changes should be moved to the Graph Widget after it gets separated in the base PR.
> 
> Also @julius-kress needs to approve the layouting changes, as i don't have the expertise to comment on that.

Yeah I like the changes as well. Darkmode on the graph makes the GUI look much cleaner. The current graph is still a mockup, but I think we can use this when implementing the actual graph 👍

2024-12-02 19:49 UTC, closed without merging